# Generated by Django 3.2.13 on 2022-06-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220615_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pepleinfo',
            options={'verbose_name': '读者'},
        ),
        migrations.AddField(
            model_name='pepleinfo',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pepleinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pepleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1),
        ),
        migrations.AlterField(
            model_name='pepleinfo',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='pepleinfo',
            table='peopleinfo',
        ),
    ]
