# Generated by Django 3.2.13 on 2022-06-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220615_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepleinfo',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='姓名'),
        ),
    ]
