# Generated by Django 3.2.13 on 2022-07-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_pepleinfo_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pepleinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='pepleinfo',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
